DECLARE @SQL NVARCHAR(MAX);
SET @SQL = N'

SELECT
 VTBFHA.BUKRS, 

VTBFHA.RFHA, 
 VTBFHA.SFGTYP, 
VTBFHA.SGSART, 
 VTBFHA.KONTRH, 
 VTBFHA.RPORTB,
 VTBFHA.WGSCHFT, 
VTBFHA.DBLFZ, 
 VTBFHA.DELFZ, 
 VTBFHA.ZUOND, 
 VTBFHA.REFER, 
 VTBFHA.MERKM, 
VTBFHA.RCOMVALCL, 
VTBFHA.FACILITYNR, 
VTBFHA.RCNTR, 
 VTBFHAPO.RFHAZB, 
 VTBFHAPO.SFHAZBA, 
 VTBFHAPO.DGUEL_KP, 
VTBFHAPO.SPAYRQ, 
 VTBFHAPO.SBEWEBE, 
VTBFHAPO.SSTORNOBWG, 
VTBFHAPO.BELNR, 
VTBFHAPO.DZTERM, 
 VTBFHAPO.BZBETR, 
VTBFHAPO.DBERVON, 
VTBFHAPO.DBERBIS, 
 VTBFHAPO.ATAGE, 
VTBFHAPO.ABASTAGE, 
VTBFHAPO.PKOND, 
 VTBFHAPO.BBASIS 

FROM SAPABAP1.VTBFHA AS VTBFHA 

INNER JOIN SAPABAP1.VTBFHAPO AS VTBFHAPO 

ON VTBFHA.BUKRS = VTBFHAPO.BUKRS
 AND VTBFHA.RFHA = VTBFHAPO.RFHA 

WHERE VTBFHAPO.SBEWEBE <> 0;

';



-- Execute the SQL on a linked server  

EXEC (@SQL) AT sap_GHP;

 

 

 